### ISSUE TITLE
EU4 building scopes

### ISSUE THREAD

**Issue by ShadyCrab** [tboby/cwtools#17]
In EU4, there is on_built and on_destroyed keys for buildings in the buildings folder, but CWTools doesnt recognise these and throws errors.

**Comment by tboby** [comment]
Added in https://github.com/tboby/cwtools-eu4-config/commit/3ad5b0625d9bef8ff0a5f024aae9eb6010fc5401

If you set the settings `rules_version` to `latest`, you'll get the update immediately :)
