### ISSUE TITLE
HOI4 - allow use of "text" in national focus

### ISSUE THREAD

**Issue by Alpinia** [tboby/cwtools#18]
A national focus' loc is usually routed to their id, but it can be diverted to another loc entry by using a "text = X" entry, which throws a false positive.
![image](https://cdn.discordapp.com/attachments/591243498825580587/655146756895408142/unknown.png)

**Comment by Alpinia** [comment]
Duplicate of #69.

**Comment by Zankoas** [comment]
This issue report: https://github.com/cwtools/cwtools-hoi4-config/issues/69
