### ISSUE TITLE
How to load dependences

### ISSUE THREAD

**Issue by ZsgsDesign** [tboby/cwtools#23]
My mod has a dependence, and it is stated correctly in the .mod file. However, CWTools doesn't load that base mod at all. If would be great if CWTools could lode mod dependencies as well. Right now there is so many false alerts and that's annoying.

**Comment by ZsgsDesign** [comment]
As a temporary solution, I suggest adding manual loading or something else, it would solve the problem as well.

**Comment by tboby** [comment]
@ZsgsDesign 
The easiest way to handle this is to add that mod to your workspace.

How it works is, for each root in your workspace:
1. If the root is called "Stellaris" (/game name) and contains "common" -> It's vanilla
2. If the root contains any of "common", "events", "interface", etc -> It's a directly opened mod folder
3. If the root contains (or is) a folder called "mod" or "mods", find all the .mod files in it, and use the paths inside the .mod files

So, if you directly open your mod folder, it ignores the `.mod` file.
If you create a VS Code workspace and add the mod folders you need, it'll load them all. :)

**Comment by ZsgsDesign** [comment]
Thank you so much. That really helps.
